<?php declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */
/** @var \Vendic\HyvaCheckoutCreateAccount\Magewire\CreateAccount $magewire */
/** @var \Vendic\HyvaCheckoutCreateAccount\ViewModel\GuestChecker $guestCheckerViewModel */
$guestCheckerViewModel = $viewModels->require(\Vendic\HyvaCheckoutCreateAccount\ViewModel\GuestChecker::class);

if (!$guestCheckerViewModel->isCustomerGuest()) {
    return;
}

?>
<div wire:model="accountExists">
    <?php if (!$magewire->accountExists): ?>
        <div class="flex gap-x-4">
            <div class="flex items-center">
                <?= $block->getChildHtml('checkbox') ?>
            </div>
            <div class="flex-1 gap-y-2">
                <label for="create-account"><?= $escaper->escapeHtml(__('Create Account')) ?></label>
            </div>
        </div>
    <?php endif; ?>
</div>
