name: Coding Standard

on: [ push, pull_request ]

jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/src

      - uses: mage-os/github-actions/coding-standard@main
        with:
          path: ${{ github.workspace }}/src
